Component home
nology-tech/wov-client-project pull request #14
Opened 2024-04-11 13:59 UTC by gordonmenzies

The home component of the App that displays a welcome message and allows the use to move to different parts of the page.

2024-04-11 16:12 UTC, Charlie-robin requested changes
Hey some minor changes to add in reach out if you need clarity on any of the points

2024-04-11 16:12 UTC, Charlie-robin commented on src/pages/Home/Home.tsx
>  import Layout from "../../components/Layout/Layout";
I think you can remove this `Layout` component it is only in the project as an example and it is not relevant to this page

2024-04-11 16:12 UTC, Charlie-robin commented on src/pages/Home/Home.tsx
>      </Layout>
You will need to add the `Navigation` component to this page,

2024-04-11 16:12 UTC, Charlie-robin commented on src/pages/Home/Home.scss
> +    border-left: 0.2rem solid #ccc;
It would help if you used a grey from the variables folder for this instead of #ccc

2024-04-11 16:12 UTC, Charlie-robin commented on src/pages/Home/Home.test.tsx
> +  it("shoulld render the paragraph"),
typo's below shoulld

2024-04-11 16:12 UTC, Charlie-robin commented on src/pages/Home/Home.test.tsx
> +    customRender(<Home />);
This test doesn't do anything and an assertion please

2024-04-11 16:12 UTC, Charlie-robin commented on src/pages/Home/Home.tsx
> +      <div className="daily-tasks" data-testid="container">
This can be a `section` instead of a div

2024-04-12 08:52 UTC, Charlie-robin commented
I have got some copy text back from Dan are you able to add this to the ticket.

```txt
Welcome to the Way of the Viking, where strength isn't measured in muscle mass, but in mentality and commitment. 



Step into a community forged by resilience and determination, where every journey begins with a single step towards empowerment.



Discover a realm where mental fortitude meets physical prowess, as we embark on a transformative quest together. 



Our comprehensive program is tailored to unleash your inner warrior, guiding you through exercises designed to sharpen both body and mind.



Join us in embracing the challenge, where every triumph is celebrated and every setback is an opportunity for growth. 



Together as Vikings, we'll conquer obstacles, break barriers, and emerge victorious on the battlefield of self-improvement.



Are you ready to rewrite your story, to forge a path towards unparalleled strength and vitality? 



Unleash your potential, ignite your passion, and let’s begin your journey into the Way of the Viking today. 



Your destiny awaits.



Could you become the next Most Valuable Viking? 


```

2024-04-12 11:38 UTC, ample-samples requested changes
Just a small change from me

2024-04-12 11:38 UTC, ample-samples commented on src/pages/Home/Home.tsx
> +          <Link to="/daily-tasks">
This should link to `/tasks` (as defined in the nav component) instead of `/daily-tasks`

2024-04-12 13:28 UTC, Charlie-robin approved these changes

2024-04-12 13:28 UTC, merged