Feature private routing
nology-tech/wov-client-project pull request #42
Opened 2024-04-18 12:21 UTC by ample-samples

- Added private routing
- `customRender` uses an options object instead of multiple arguments
- Added `wrapWithAuthProvider` to `testUtils`

2024-04-18 16:34 UTC, Charlie-robin requested changes
Hey great work! this is a cool ticket and feature to get in.

I have some small changes and things to consider, we can catch up on the testing part at some point tomorrow.

2024-04-18 16:34 UTC, Charlie-robin commented on src/utils/testUtils.tsx
We can catch up about this tomorrow but I would refactor the file to be something like the code below

```tsx
import { render } from "@testing-library/react";
import { BrowserRouter as Router } from "react-router-dom";
import {
  FirestoreContext,
  FirestoreContextProps,
} from "../context/FirestoreProvider/FirestoreProvider";
import {
  AuthContext,
  AuthContextProps,
} from "../context/AuthProvider/AuthProvider";

type Options = {
  useRouting?: boolean;
  firestoreContext?: FirestoreContextProps;
  authContext?: AuthContextProps;
};

const defaultOptions: Options = {
  useRouting: true,
  firestoreContext: undefined,
  authContext: undefined,
};
// calendar
// active tasks
// leaderboard
export const customRender = (
  ui: JSX.Element,
  { firestoreContext, useRouting, authContext } = defaultOptions
) => {
  // wrap components in routing if requested
  let uiResult = ui;

  if (firestoreContext) {
    uiResult = wrapWithFirestoreProvider(ui, firestoreContext);
  }

  if (useRouting) {
    uiResult = wrapWithRouting(uiResult);
  }

  if (authContext) {
    uiResult = wrapWithAuthProvider(uiResult, authContext);
  }

  // use RTL's render function to return the test component
  return render(uiResult);
};

const wrapWithRouting = (ui: JSX.Element): JSX.Element => {
  return <Router>{ui}</Router>;
};

const wrapWithAuthProvider = (
  ui: JSX.Element,
  options: AuthContextProps
): JSX.Element => {
  const defaultAuthContext: AuthContextProps = {
    loginUser: (_, __) => Promise.resolve({ error: null }),
    logoutUser: () => null,
    isAuthenticated: true,
    userUID: "12345",
  };
  console.log("Wrapping");
  return (
    <AuthContext.Provider value={{ ...defaultAuthContext, ...options }}>
      {ui}
    </AuthContext.Provider>
  );
};

const wrapWithFirestoreProvider = (
  ui: JSX.Element,
  firestoreContext: FirestoreContextProps
): JSX.Element => {
  const defaultFireStoreContext = {
    getActiveTasks: (_: string) => Promise.resolve([]),
    getCompletedTasks: (_: string) => Promise.resolve([]),
    getLeaderboard: (_: string) => Promise.resolve([]),
  };

  return (
    <FirestoreContext.Provider
      value={{ ...defaultFireStoreContext, ...firestoreContext }}
    >
      {ui}
    </FirestoreContext.Provider>
  );
};
```

It makes it easier to test as you can pass in different contexts to the render function. 

```tsx
import { screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import ErrorPage from "./ErrorPage";
import { customRender } from "../../utils/testUtils";
import { AuthContextProps } from "../../context/AuthProvider/AuthProvider";

describe("ErrorPage", () => {
  it("should render content properly "),
    () => {
      customRender(<ErrorPage />);
      const homeButton = screen.getByText("Home");
      const errorMessage = screen.getByText(
        "OOPS. LOOKS LIKE YOU'VE TAKEN A WRONG TURN."
      );
      expect(errorMessage).toBeInTheDocument();
      expect(homeButton).toBeInTheDocument();
    };

  it("should redirect to /home when unauthenticated and 'home' button is clicked", async () => {
    const { getByText } = customRender(<ErrorPage />, {
      useRouting: true,
      authContext: {
        isAuthenticated: false,
      } as AuthContextProps,
    });
    const home = getByText("Home");
    await userEvent.click(home);
    expect(window.location.pathname).toEqual("/auth");
  });

  it("should redirect to / when 'home' authenticated and 'home' button is clicked", async () => {
    const { getByText } = customRender(<ErrorPage />, {
      useRouting: true,
      authContext: {} as AuthContextProps,
    });
    const home = getByText("Home");
    await userEvent.click(home);
    expect(window.location.pathname).toEqual("/");
  });
});

```

2024-04-19 08:48 UTC, ample-samples commented on src/pages/Leaderboard/Leaderboard.tsx
> +    const filterNoName = sortedUsers.filter((user) => user.name)
We did this to fix errors on the leaderboard page due to undefined names, should we remove this line?

2024-04-19 11:02 UTC, Charlie-robin approved these changes

2024-04-19 11:02 UTC, merged