Component create group
nology-tech/wov-client-project pull request #67
Opened 2024-05-02 10:56 UTC by Nx-Makomva

2024-05-02 11:09 UTC, JoshS1234 commented on src/components/CreateGroup/CreateGroup.tsx
Remove the button in lines 36-39, this shouldn't be present in this component.

2024-05-02 11:10 UTC, JoshS1234 commented on src/App.tsx
Remove line 31 and 17. This component shouldn't be here currently, as it will be nested in the create page (which hasn't been added yet, will be added by Callum and Bethany)

2024-05-02 11:13 UTC, JoshS1234 commented on src/components/CreateGroup/CreateGroup.tsx
Remove comment on line 42

2024-05-02 11:18 UTC, JoshS1234 commented on src/components/CreateGroup/CreateGroup.tsx
For line 26 and 29, rather than displaying errors/issues in the console. Have errors shown on the screen in red (Eg: "Group cannot be blank" appears above the "create" button)

2024-05-02 11:35 UTC, JoshS1234 commented on src/components/CreateGroup/CreateGroup.tsx
In handleCreateGroup, there needs to be a check for if there is a pre-existing tribe with that name, at the moment it just overwrites it.

There should also be an acknowledgement that it has succeeded, like a message appearing in green saying "tribe created".

2024-05-02 11:38 UTC, JoshS1234 requested changes
Reviewed with some changes

2024-05-02 14:32 UTC, msalehprofile commented on src/components/CreateGroup/CreateGroup.scss
Please could the labels above the inputs be changed to left aligned

2024-05-02 14:35 UTC, msalehprofile commented on src/components/CreateGroup/CreateGroup.tsx
Instead of the error message saying what is missing, it might be cleaner to just say e.g. "This is a required field"

2024-05-02 14:40 UTC, msalehprofile commented on src/components/CreateGroup/CreateGroup.tsx
Doesnt look like the check for repeated tribe name is working, please could you have a check

2024-05-02 14:41 UTC, msalehprofile requested changes
Please make sure this conditionally renders in line 34 of the 'create' page

2024-05-03 08:36 UTC, msalehprofile approved these changes

2024-05-03 08:37 UTC, msalehprofile approved these changes

2024-05-03 08:38 UTC, JoshS1234 approved these changes

2024-05-03 08:38 UTC, merged