Component header
nology-tech/wov-client-project pull request #9
Opened 2024-04-10 11:47 UTC by chae-la

Two components created: Header and HeaderHome (HeaderHome only used in home page)

2024-04-10 13:46 UTC, ample-samples requested changes

2024-04-10 13:46 UTC, ample-samples commented on src/components/Header/Header.scss
> +  }
The size of the header is far too large on screen sizes from tablet to desktop, ik we don't have wireframes to work from for larger screen sizes so just get this sized sensibly

2024-04-10 13:46 UTC, ample-samples commented on src/components/Header/Header.stories.tsx
There is a good story component for the header, can you add another for the homeHeader please

2024-04-10 13:46 UTC, ample-samples commented on src/components/Header/Header.stories.tsx
> +  decorators: [withRouter],
This meta variable is missing autodocs, please add `tags: ["autodocs"],` to the meta variable

2024-04-10 13:46 UTC, ample-samples commented on src/components/HeaderHome/HeaderHome.stories.tsx
Using npm run storybook, I can't see the HeaderHome component 🤔 can you look into a solution for this please

2024-04-10 13:56 UTC, Charlie-robin requested changes

2024-04-10 13:56 UTC, Charlie-robin commented on src/components/HeaderHome/HeaderHome.tsx
> +  date?: string;
I think that these should not be optional or if they are optional you need to conditionally render the img and p tag related to them.

2024-04-10 13:56 UTC, Charlie-robin commented on src/components/HeaderHome/HeaderHome.stories.tsx
> +export const WithDate: Story = {
It is a simple component so I do not think you need 3 stories for it.

2024-04-11 08:00 UTC, Charlie-robin commented on src/components/HeaderHome/HeaderHome.stories.tsx
> +export const WithDate: Story = {
I think you only need this story as that component is only used once and is given all of its props. 

```js
export const WithLocationAndImage: Story = {
    args: {
      date: "29 April 2024",
      location: "Malvern Hills",
      image: "https://s3-alpha-sig.figma.com/img/9003/31aa/6dd32f49cc5bf6f29932b0481a2af856?Expires=1713744000&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=FrjVJj2XFAnoifxYaGoHI0CfbBKprDFMJqDeV1ur21HRwi~j1ZYNRCW-3LPZchYU-brnUydqEOyJ8eUfwA9nB6ATjPomas0~pIPizR9gu2Je79kN9EP1pmgZjI3K6aKUXz7IoMgEErOcHxjXyt42pBlu1Ym8~HfjFPcrLW1igtrvA6JO9y997SJDeldC1ENK0Y8myy9wViW54XoUX1ripSdMlgX9NG2pa--C1P1eafFfIzyQyWrB-Uz8e9eWq0va0JvsDInxsaRT1wOvxHVAxGc~nyK5VJwcSVlplUeTEEL~fMMPrn31K8dbJHlxd0bGEGobas-1vWFzvzv~01QwUw__"
    },
  };
```

This means that you can remove this story as it is not necessary 

```js
export const WithDate: Story = {
  args: {
    date: "29 April 2024",
  },
};
```

2024-04-11 08:17 UTC, Charlie-robin requested changes

2024-04-11 08:17 UTC, Charlie-robin commented on src/components/Header/Header.tsx
> +        <h4 className="header__title-div header__title-div--title">{title}</h4>
I don't think this needs to be a prop as it is WAY OF THE VIKING on all of the pages

2024-04-11 08:17 UTC, Charlie-robin commented on src/components/Header/Header.tsx
> +            src={profileImage}
I think that we need to handle if the profileImage is not passed as a prop, perhaps we have a default image to use if it is undefined given?

2024-04-11 09:28 UTC, Charlie-robin approved these changes

2024-04-11 09:29 UTC, merged